[font]

normal = {family="JetBrains Mono", stype= "Regular"}
bold = {family = "JetBrains Mono", style = "Bold" }
italic = {family = "JetBrains Mono", style = "Italic"  }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic"  }
size = 14.0

[colors.primary]
background = '#0A0A0A'

[colors.normal]
# black is gray0
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#ffAA88'
blue = '#7788AA'
magenta = '#D7007D'
# cyan is set to lack
cyan = '#708090' 
# white is set to luster
white = '#DEEEED'
