[font]
size = 14.0
[font.normal]
family="FiraMonoNerdFont" 
stype= "Regular"

[font.bold]
family = "FiraMonoNerdFont"
style = "Bold"
[font.italic]
family = "FiraMonoNerdFont"
style = "Italic"  
[font.bold_italic]
family = "FiraMonoNerdFont"
style = "Bold Italic"

[colors.primary]
background = '#0A0A0A'

[colors.normal]
# black is gray0
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#ffAA88'
blue = '#7788AA'
magenta = '#D7007D'
# cyan is set to lack
cyan = '#708090' 
# white is set to luster
white = '#DEEEED'
