local builtin = require('telescope.builtin')
require("telescope")
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
vim.keymap.set('n', '<leader>vm', builtin.keymaps, {})

vim.keymap.set('n', '<leader>pb', builtin.current_buffer_fuzzy_find, {})
vim.keymap.set('n', '<leader>pt', builtin.treesitter, {})
