#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then 
    selected=$(find ~/ ~/work/dev ~/personal ~/personal/go ~/personal/STAS/ ~/personal/clojure /media/a.belo/And\ VOL/ -mindepth 1 -maxdepth 1 -type d | fzf)
elif [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find "$@" -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds $selected_name -c $selected
    tmux new-window -d -t $selected_name:3 -c $selected -n k8s
    tmux new-window -d -t $selected_name:4 -c $selected -n misc
    tmux new-window -d -t $selected_name:2 -c $selected -n editor
    tmux attach -t $selected_name:2
    exit 0
fi

have_session=$(tmux has-session -t=$selected_name 2> /dev/null)
if ! have_session; then
    tmux new-session -ds $selected_name -c $selected -n zsh
    tmux new-window -d -t $selected_name:3 -c $selected -n k8s
    tmux new-window -d -t $selected_name:4 -c $selected -n misc
    tmux new-window -t $selected_name:2 -c $selected -n editor
fi

if [[ -z $TMUX ]] ; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi

